"""empty message

Revision ID: e3e506338b66
Revises: a5cffa318ac2
Create Date: 2024-09-24 01:21:36.627925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e506338b66'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('clima', sa.String(length=250), nullable=False),
    sa.Column('diametro', sa.Float(), nullable=False),
    sa.Column('poblacion', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('marca', sa.String(length=250), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('pasajeros', sa.Integer(), nullable=False),
    sa.Column('tripulacion', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('planeta_origen', sa.Integer(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('unidades_altura', sa.String(length=250), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('unidades_peso', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['planeta_origen'], ['planeta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('personaje', sa.Integer(), nullable=True),
    sa.Column('planeta', sa.Integer(), nullable=True),
    sa.Column('vehiculo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personaje'], ['personaje.id'], ),
    sa.ForeignKeyConstraint(['planeta'], ['planeta.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehiculo'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=250), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')

    op.drop_table('favorites')
    op.drop_table('personaje')
    op.drop_table('vehiculo')
    op.drop_table('planeta')
    # ### end Alembic commands ###
